BEGIN;
CREATE SEQUENCE "public"."parametro_idparametro_seq" INCREMENT BY 1 START WITH 1 OWNED BY "public"."parametro"."idparametro";
CREATE SEQUENCE "public"."trilha_idtrilha_seq" INCREMENT BY 1 START WITH 1 OWNED BY "public"."trilha"."idtrilha";
CREATE SEQUENCE "public"."unidade_idunidade_seq" INCREMENT BY 1 START WITH 1 OWNED BY "public"."unidade"."idunidade";
ALTER TABLE "public"."parametro" ADD CONSTRAINT "pk_idparametro" PRIMARY KEY ("idparametro");
ALTER TABLE "public"."trilha" ADD CONSTRAINT "pk_trilha" PRIMARY KEY ("idtrilha");
ALTER TABLE "public"."unidade" ADD CONSTRAINT "pk_unidade" PRIMARY KEY ("idunidade");
CREATE SEQUENCE "auditing"."alteracoes_idalteracoes_seq" INCREMENT BY 1 START WITH 1 OWNED BY "auditing"."alteracoes"."idalteracoes";
CREATE SEQUENCE "auditing"."log_idlog_seq" INCREMENT BY 1 START WITH 1 OWNED BY "auditing"."log"."idlog";
CREATE SEQUENCE "auditing"."logerror_idlogerro_seq" INCREMENT BY 1 START WITH 1 OWNED BY "auditing"."logerror"."idlogerro";
ALTER TABLE "auditing"."alteracoes" ADD PRIMARY KEY ("idalteracoes");
CREATE SEQUENCE "sgbd"."basededados_idbasededados_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."basededados"."idbasededados";
CREATE SEQUENCE "sgbd"."bdmysql_idbdmysql_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdmysql"."idbdmysql";
CREATE SEQUENCE "sgbd"."bdoracle_iddboracle_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdoracle"."iddboracle";
CREATE SEQUENCE "sgbd"."bdoracletipo_idbdoracletipo_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdoracletipo"."idbdoracletipo";
CREATE SEQUENCE "sgbd"."bdpostgres_idbdpostgres_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdpostgres"."idbdpostgres";
CREATE SEQUENCE "sgbd"."bdsqlserver_idbdsqlserver_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdsqlserver"."idbdsqlserver";
CREATE SEQUENCE "sgbd"."bdtabela_idbdtabela_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdtabela"."idbdtabela";
CREATE SEQUENCE "sgbd"."bdtamanho_idbdtamanho_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."bdtamanho"."idbdtamanho";
CREATE SEQUENCE "sgbd"."cluster_idcluster_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."cluster"."idcluster";
CREATE SEQUENCE "sgbd"."clusterno_idclusterno_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."clusterno"."idclusterno";
CREATE SEQUENCE "sgbd"."clustertipo_idclustertipo_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."clustertipo"."idclustertipo";
CREATE SEQUENCE "sgbd"."instancia_idinstancia_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."instancia"."idinstancia";
CREATE SEQUENCE "sgbd"."instancia_mysql_idinstancia_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."instancia_mysql"."idinstancia";
CREATE SEQUENCE "sgbd"."instancia_oracle_idinstancia_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."instancia_oracle"."idinstancia";
CREATE SEQUENCE "sgbd"."instancia_postgresql_idinstancia_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."instancia_postgresql"."idinstancia";
CREATE SEQUENCE "sgbd"."instancia_sqlserver_idinstancia_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."instancia_sqlserver"."idinstancia";
CREATE SEQUENCE "sgbd"."loginsqlserver_idloginsqlserver_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."loginsqlserver"."idloginsqlserver";
CREATE SEQUENCE "sgbd"."rolemembrosqlserver_idrolemembrosqlserver_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."rolemembrosqlserver"."idrolemembrosqlserver";
CREATE SEQUENCE "sgbd"."tbcoluna_idtbcoluna_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."tbcoluna"."idtbcoluna";
CREATE SEQUENCE "sgbd"."tbindex_idtbindex_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."tbindex"."idtbindex";
CREATE SEQUENCE "sgbd"."tbindexfrag_idtbindexfrag_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."tbindexfrag"."idtbindexfrag";
CREATE SEQUENCE "sgbd"."tbindexstats_idtbindexstats_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."tbindexstats"."idtbindexstats";
CREATE SEQUENCE "sgbd"."tbstarts_idtbstarts_seq" INCREMENT BY 1 START WITH 1 OWNED BY "sgbd"."tbstarts"."idtbstarts";
ALTER TABLE "sgbd"."bdmysql" ADD CONSTRAINT "pk_bdmysql_idbdmysql" PRIMARY KEY ("idbdmysql");
ALTER TABLE "sgbd"."bdoracle" ADD CONSTRAINT "pk_bdoracle_iddboracle" PRIMARY KEY ("iddboracle");
ALTER TABLE "sgbd"."bdoracletipo" ADD CONSTRAINT "pk_dboracletipo_iddboracletipo" PRIMARY KEY ("idbdoracletipo");
ALTER TABLE "sgbd"."bdpostgres" ADD CONSTRAINT "pk_bdpostgres_idbdpostgres" PRIMARY KEY ("idbdpostgres");
ALTER TABLE "sgbd"."bdsqlserver" ADD CONSTRAINT "pk_bdsqlserver_idbdsqlserver" PRIMARY KEY ("idbdsqlserver");
ALTER TABLE "sgbd"."bdtabela" ADD CONSTRAINT "pk_bdtabela_idbdtabela" PRIMARY KEY ("idbdtabela");
ALTER TABLE "sgbd"."bdtamanho" ADD PRIMARY KEY ("idbdtamanho");
ALTER TABLE "sgbd"."loginsqlserver" ADD PRIMARY KEY ("idloginsqlserver");
ALTER TABLE "sgbd"."rolemembrosqlserver" ADD PRIMARY KEY ("idrolemembrosqlserver");
ALTER TABLE "sgbd"."tbcoluna" ADD PRIMARY KEY ("idtbcoluna");
ALTER TABLE "sgbd"."tbindex" ADD PRIMARY KEY ("idtbindex");
ALTER TABLE "sgbd"."tbindexfrag" ADD PRIMARY KEY ("idtbindexfrag");
ALTER TABLE "sgbd"."tbindexstats" ADD PRIMARY KEY ("idtbindexstats");
ALTER TABLE "sgbd"."tbstarts" ADD CONSTRAINT "pk_tbstarts_idbdtabela" PRIMARY KEY ("idtbstarts");
ALTER TABLE "sgbd"."vm_tbindex" ADD PRIMARY KEY ("idtbindex");
ALTER TABLE "sgbd"."vm_tbindexfrag" ADD PRIMARY KEY ("idtbindex");
ALTER TABLE "sgbd"."vm_tbindexstats" ADD PRIMARY KEY ("idtbindex");
ALTER TABLE "sgbd"."vm_tbstarts" ADD PRIMARY KEY ("idbdtabela");
ALTER TABLE "sgbd"."basededados" ADD CONSTRAINT "pk_basededados_idbasededados" PRIMARY KEY ("idbasededados");
ALTER TABLE "sgbd"."cluster" ADD CONSTRAINT "pk_sdcluster_idcluster" PRIMARY KEY ("idcluster");
ALTER TABLE "sgbd"."clusterno" ADD CONSTRAINT "pk_clusterno_idclusterno" PRIMARY KEY ("idclusterno");
ALTER TABLE "sgbd"."clustertipo" ADD CONSTRAINT "pk_clustertipo_idclustertipo" PRIMARY KEY ("idclustertipo");
ALTER TABLE "sgbd"."instancia" ADD CONSTRAINT "pk_instancia_iddbinstancia" PRIMARY KEY ("idinstancia");
CREATE SEQUENCE "serverhost"."disk_iddisk_seq" INCREMENT BY 1 START WITH 1 OWNED BY "serverhost"."disk"."iddisk";
CREATE SEQUENCE "serverhost"."disktamanho_iddisktamanho_seq" INCREMENT BY 1 START WITH 1 OWNED BY "serverhost"."disktamanho"."iddisktamanho";
CREATE SEQUENCE "serverhost"."servidor_idshservidor_seq" INCREMENT BY 1 START WITH 1 OWNED BY "serverhost"."servidor"."idshservidor";
ALTER TABLE "serverhost"."disk" ADD PRIMARY KEY ("iddisk");
ALTER TABLE "serverhost"."disktamanho" ADD PRIMARY KEY ("iddisktamanho");
ALTER TABLE "serverhost"."servidor" ADD CONSTRAINT "pk_servidor_idservidor" PRIMARY KEY ("idshservidor");
CREATE SEQUENCE "app"."aplicativo_idaplicativo_seq" INCREMENT BY 1 START WITH 1 OWNED BY "app"."aplicativo"."idaplicativo";
CREATE SEQUENCE "app"."appambiente_idappambiente_seq" INCREMENT BY 1 START WITH 1 OWNED BY "app"."appambiente"."idappambiente";
CREATE SEQUENCE "app"."appstringconect_idappstringconect_seq" INCREMENT BY 1 START WITH 1 OWNED BY "app"."appstringconect"."idappstringconect";
CREATE SEQUENCE "app"."stbasededados_idstbasededados_seq" INCREMENT BY 1 START WITH 1 OWNED BY "app"."stbasededados"."idstbasededados";
ALTER TABLE "app"."aplicativo" ADD CONSTRAINT "pk_aplicativo_idaplicativo" PRIMARY KEY ("idaplicativo");
ALTER TABLE "app"."appambiente" ADD CONSTRAINT "pk_appambiente_idappambiente" PRIMARY KEY ("idappambiente");
ALTER TABLE "app"."appstringconect" ADD CONSTRAINT "pk_appstringconect_idappstringconect" PRIMARY KEY ("idappstringconect");
ALTER TABLE "app"."stbasededados" ADD CONSTRAINT "pk_stbasededados_idstbasededados" PRIMARY KEY ("idstbasededados");
ALTER TABLE "sgbd"."bdmysql" ADD CONSTRAINT "fk_bdmysql_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."bdoracle" ADD CONSTRAINT "fk_bdoracle_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."bdoracle" ADD CONSTRAINT "fk_dboracletipo_basededados" FOREIGN KEY ("idbdoracletipo") REFERENCES "sgbd"."bdoracletipo" ( "idbdoracletipo");
ALTER TABLE "sgbd"."bdpostgres" ADD CONSTRAINT "fk_bdpostgres_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."bdsqlserver" ADD CONSTRAINT "fk_bdsqlserver_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."bdtabela" ADD CONSTRAINT "fk_bdtabela_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."bdtamanho" ADD CONSTRAINT "fk_basededados_idbasededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."loginsqlserver" ADD CONSTRAINT "fk_loginsqlserver_instancia " FOREIGN KEY ("idinstancia") REFERENCES "sgbd"."instancia" ( "idinstancia");
ALTER TABLE "sgbd"."rolemembrosqlserver" ADD CONSTRAINT "fk_rolemembrosqlserver_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "sgbd"."tbcoluna" ADD CONSTRAINT "fk_tbcoluna_bdtabela" FOREIGN KEY ("idbdtabela") REFERENCES "sgbd"."bdtabela" ( "idbdtabela");
ALTER TABLE "sgbd"."tbindex" ADD CONSTRAINT "fk_tbindex_bdtabela" FOREIGN KEY ("idbdtabela") REFERENCES "sgbd"."bdtabela" ( "idbdtabela");
ALTER TABLE "sgbd"."tbindexfrag" ADD CONSTRAINT "fk_tbindexfrag_tbindex" FOREIGN KEY ("idtbindex") REFERENCES "sgbd"."tbindex" ( "idtbindex");
ALTER TABLE "sgbd"."tbindexstats" ADD CONSTRAINT "fk_tbindexstats_tbindex" FOREIGN KEY ("idtbindex") REFERENCES "sgbd"."tbindex" ( "idtbindex");
ALTER TABLE "sgbd"."tbstarts" ADD CONSTRAINT "fk_tbstarts_bdtabela" FOREIGN KEY ("idbdtabela") REFERENCES "sgbd"."bdtabela" ( "idbdtabela");
ALTER TABLE "sgbd"."basededados" ADD CONSTRAINT "fk_basededados_trilha" FOREIGN KEY ("idtrilha") REFERENCES "public"."trilha" ( "idtrilha");
ALTER TABLE "sgbd"."basededados" ADD CONSTRAINT "fk_servidor_basededados" FOREIGN KEY ("idinstancia") REFERENCES "sgbd"."instancia" ( "idinstancia");
ALTER TABLE "sgbd"."cluster" ADD CONSTRAINT "fk_cluster_idclustertipo" FOREIGN KEY ("idclustertipo") REFERENCES "sgbd"."clustertipo" ( "idclustertipo");
ALTER TABLE "sgbd"."clusterno" ADD CONSTRAINT "fk_clusterno_cluster" FOREIGN KEY ("idcluster") REFERENCES "sgbd"."cluster" ( "idcluster");
ALTER TABLE "sgbd"."clusterno" ADD CONSTRAINT "fk_clusterno_servidor" FOREIGN KEY ("idshservidor") REFERENCES "serverhost"."servidor" ( "idshservidor");
ALTER TABLE "sgbd"."instancia" ADD CONSTRAINT "fk_instancia_cluster" FOREIGN KEY ("idcluster") REFERENCES "sgbd"."cluster" ( "idcluster");
ALTER TABLE "sgbd"."instancia" ADD CONSTRAINT "fk_instancia_servidor" FOREIGN KEY ("idshservidor") REFERENCES "serverhost"."servidor" ( "idshservidor");
ALTER TABLE "sgbd"."instancia" ADD CONSTRAINT "fk_instancia_trilha" FOREIGN KEY ("idtrilha") REFERENCES "public"."trilha" ( "idtrilha");
ALTER TABLE "serverhost"."disk" ADD CONSTRAINT "fk_ldisk_servidor" FOREIGN KEY ("idshservidor") REFERENCES "serverhost"."servidor" ( "idshservidor");
ALTER TABLE "serverhost"."disktamanho" ADD CONSTRAINT "fk_ldisk_disktamanho" FOREIGN KEY ("iddisk") REFERENCES "serverhost"."disk" ( "iddisk");
ALTER TABLE "serverhost"."servidor" ADD CONSTRAINT "fk_serverhost_trilha" FOREIGN KEY ("idtrilha") REFERENCES "public"."trilha" ( "idtrilha");
ALTER TABLE "app"."appambiente" ADD CONSTRAINT "fk_appambiente_aplicativo" FOREIGN KEY ("idaplicativo") REFERENCES "app"."aplicativo" ( "idaplicativo");
ALTER TABLE "app"."appambiente" ADD CONSTRAINT "fk_appambiente_serverhost" FOREIGN KEY ("idshservidor") REFERENCES "serverhost"."servidor" ( "idshservidor");
ALTER TABLE "app"."appambiente" ADD CONSTRAINT "fk_appambiente_trilha" FOREIGN KEY ("idtrilha") REFERENCES "public"."trilha" ( "idtrilha");
ALTER TABLE "app"."appstringconect" ADD CONSTRAINT "fk_appambiente_appstringconect" FOREIGN KEY ("idappambiente") REFERENCES "app"."appambiente" ( "idappambiente");
ALTER TABLE "app"."stbasededados" ADD CONSTRAINT "fk_stbasededados_appstringconect" FOREIGN KEY ("idappstringconect") REFERENCES "app"."appstringconect" ( "idappstringconect");
ALTER TABLE "app"."stbasededados" ADD CONSTRAINT "fk_stbasededados_basededados" FOREIGN KEY ("idbasededados") REFERENCES "sgbd"."basededados" ( "idbasededados");
ALTER TABLE "public"."parametro" ALTER COLUMN "idparametro" SET DEFAULT nextval('"public"."parametro_idparametro_seq"');
ALTER TABLE "public"."trilha" ALTER COLUMN "idtrilha" SET DEFAULT nextval('"public"."trilha_idtrilha_seq"');
ALTER TABLE "public"."unidade" ALTER COLUMN "idunidade" SET DEFAULT nextval('"public"."unidade_idunidade_seq"');
ALTER TABLE "auditing"."alteracoes" ALTER COLUMN "idalteracoes" SET DEFAULT nextval('"auditing"."alteracoes_idalteracoes_seq"');
ALTER TABLE "auditing"."log" ALTER COLUMN "idlog" SET DEFAULT nextval('"auditing"."log_idlog_seq"');
ALTER TABLE "auditing"."logerror" ALTER COLUMN "idlogerro" SET DEFAULT nextval('"auditing"."logerror_idlogerro_seq"');
ALTER TABLE "sgbd"."bdmysql" ALTER COLUMN "idbdmysql" SET DEFAULT nextval('"sgbd"."bdmysql_idbdmysql_seq"');
ALTER TABLE "sgbd"."bdoracle" ALTER COLUMN "iddboracle" SET DEFAULT nextval('"sgbd"."bdoracle_iddboracle_seq"');
ALTER TABLE "sgbd"."bdoracletipo" ALTER COLUMN "idbdoracletipo" SET DEFAULT nextval('"sgbd"."bdoracletipo_idbdoracletipo_seq"');
ALTER TABLE "sgbd"."bdpostgres" ALTER COLUMN "idbdpostgres" SET DEFAULT nextval('"sgbd"."bdpostgres_idbdpostgres_seq"');
ALTER TABLE "sgbd"."bdsqlserver" ALTER COLUMN "idbdsqlserver" SET DEFAULT nextval('"sgbd"."bdsqlserver_idbdsqlserver_seq"');
ALTER TABLE "sgbd"."bdtabela" ALTER COLUMN "idbdtabela" SET DEFAULT nextval('"sgbd"."bdtabela_idbdtabela_seq"');
ALTER TABLE "sgbd"."bdtamanho" ALTER COLUMN "idbdtamanho" SET DEFAULT nextval('"sgbd"."bdtamanho_idbdtamanho_seq"');
ALTER TABLE "sgbd"."loginsqlserver" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "sgbd"."loginsqlserver" ALTER COLUMN "idloginsqlserver" SET DEFAULT nextval('"sgbd"."loginsqlserver_idloginsqlserver_seq"');
ALTER TABLE "sgbd"."rolemembrosqlserver" ALTER COLUMN "idrolemembrosqlserver" SET DEFAULT nextval('"sgbd"."rolemembrosqlserver_idrolemembrosqlserver_seq"');
ALTER TABLE "sgbd"."tbcoluna" ALTER COLUMN "idtbcoluna" SET DEFAULT nextval('"sgbd"."tbcoluna_idtbcoluna_seq"');
ALTER TABLE "sgbd"."tbindex" ALTER COLUMN "idtbindex" SET DEFAULT nextval('"sgbd"."tbindex_idtbindex_seq"');
ALTER TABLE "sgbd"."tbindexfrag" ALTER COLUMN "idtbindexfrag" SET DEFAULT nextval('"sgbd"."tbindexfrag_idtbindexfrag_seq"');
ALTER TABLE "sgbd"."tbindexstats" ALTER COLUMN "idtbindexstats" SET DEFAULT nextval('"sgbd"."tbindexstats_idtbindexstats_seq"');
ALTER TABLE "sgbd"."tbstarts" ALTER COLUMN "idtbstarts" SET DEFAULT nextval('"sgbd"."tbstarts_idtbstarts_seq"');
ALTER TABLE "sgbd"."basededados" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "sgbd"."basededados" ALTER COLUMN "idbasededados" SET DEFAULT nextval('"sgbd"."basededados_idbasededados_seq"');
ALTER TABLE "sgbd"."cluster" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "sgbd"."cluster" ALTER COLUMN "idcluster" SET DEFAULT nextval('"sgbd"."cluster_idcluster_seq"');
ALTER TABLE "sgbd"."clusterno" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "sgbd"."clusterno" ALTER COLUMN "idclusterno" SET DEFAULT nextval('"sgbd"."clusterno_idclusterno_seq"');
ALTER TABLE "sgbd"."clustertipo" ALTER COLUMN "idclustertipo" SET DEFAULT nextval('"sgbd"."clustertipo_idclustertipo_seq"');
ALTER TABLE "sgbd"."instancia" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "sgbd"."instancia" ALTER COLUMN "cluster" SET DEFAULT false;
ALTER TABLE "sgbd"."instancia" ALTER COLUMN "estanciaativo" SET DEFAULT true;
ALTER TABLE "sgbd"."instancia" ALTER COLUMN "idinstancia" SET DEFAULT nextval('"sgbd"."instancia_idinstancia_seq"');
ALTER TABLE "sgbd"."instancia_mysql" ALTER COLUMN "idinstancia" SET DEFAULT nextval('"sgbd"."instancia_mysql_idinstancia_seq"');
ALTER TABLE "sgbd"."instancia_oracle" ALTER COLUMN "idinstancia" SET DEFAULT nextval('"sgbd"."instancia_oracle_idinstancia_seq"');
ALTER TABLE "sgbd"."instancia_sqlserver" ALTER COLUMN "idinstancia" SET DEFAULT nextval('"sgbd"."instancia_sqlserver_idinstancia_seq"');
ALTER TABLE "sgbd"."instancia_postgresql" ALTER COLUMN "idinstancia" SET DEFAULT nextval('"sgbd"."instancia_postgresql_idinstancia_seq"');
ALTER TABLE "serverhost"."disk" ALTER COLUMN "iddisk" SET DEFAULT nextval('"serverhost"."disk_iddisk_seq"');
ALTER TABLE "serverhost"."disktamanho" ALTER COLUMN "iddisktamanho" SET DEFAULT nextval('"serverhost"."disktamanho_iddisktamanho_seq"');
ALTER TABLE "serverhost"."servidor" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "serverhost"."servidor" ALTER COLUMN "idshservidor" SET DEFAULT nextval('"serverhost"."servidor_idshservidor_seq"');
ALTER TABLE "app"."aplicativo" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "app"."aplicativo" ALTER COLUMN "idaplicativo" SET DEFAULT nextval('"app"."aplicativo_idaplicativo_seq"');
ALTER TABLE "app"."appambiente" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "app"."appambiente" ALTER COLUMN "idappambiente" SET DEFAULT nextval('"app"."appambiente_idappambiente_seq"');
ALTER TABLE "app"."appstringconect" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "app"."appstringconect" ALTER COLUMN "idappstringconect" SET DEFAULT nextval('"app"."appstringconect_idappstringconect_seq"');
ALTER TABLE "app"."stbasededados" ALTER COLUMN "ativo" SET DEFAULT true;
ALTER TABLE "app"."stbasededados" ALTER COLUMN "idstbasededados" SET DEFAULT nextval('"app"."stbasededados_idstbasededados_seq"');
COMMIT;
